Add list of publications
cncf/tag-security pull request #1027
Opened 2023-01-13 18:03 UTC by szh

Signed-off-by: Shlomo Heigh <shlomo.heigh@cyberark.com>

Resolves #1026

2023-01-13 20:33 UTC, mnm678 approved these changes

2023-01-14 01:13 UTC, ragashreeshekar commented on PUBLICATIONS.md
> +- [Spreadsheet](https://docs.google.com/spreadsheets/d/1GUohOTlLw9FKUQ3O23X7ypvJLXN-B3veJGe6YE6JYfU/edit?usp=sharing)
Thanks @szh for this PR. Much appreciated. 
Please incorporate the suggestions in this comment to reference some more efforts from the community 
https://github.com/cncf/tag-security/issues/1026#issuecomment-1382619123

2023-01-14 01:14 UTC, ragashreeshekar requested changes
Thanks @szh for this PR. Much appreciated.
Please incorporate the suggestions in this comment to reference some more efforts from the community
https://github.com/cncf/tag-security/issues/1026#issuecomment-1382619123

2023-01-17 14:11 UTC, szh commented
@ragashreeshekar I added the translations of the CNSWP and the security assessments. #110 seems to be a bit broader than this - it also wants a broader overview of the TAG and a static site. Is that the direction we want to go in?

2023-01-17 16:31 UTC, ragashreeshekar commented
> @ragashreeshekar I added the translations of the CNSWP and the security assessments. #110 seems to be a bit broader than this - it also wants a broader overview of the TAG and a static site. Is that the direction we want to go in?

Thanks @szh, this addresses the requirements of central repo of the TAG contributions. LGTM. 
Microsite from https://github.com/cncf/tag-security/issues/110 is outside of the scope of https://github.com/cncf/tag-security/issues/1026.

2023-01-17 16:31 UTC, ragashreeshekar approved these changes

2023-01-17 16:35 UTC, merged