OpenTelemetry Project Security Self-Assessment
cncf/tag-security pull request #1185
Opened 2023-12-07 00:05 UTC by PrathamGupta

Created and added first draft of the [OpenTelemetry](https://opentelemetry.io) Project Security Self-Assessment.
Please feel free to share any thoughts on the self-assessment.

2023-12-08 14:43 UTC, eddie-knight commented
Hi there! I'm just getting started looking at your pull request, and I noticed the DCO check is failing.

You can look at the checks section of the PR (I believe it should always be below the last comment) and look for a red X highlighting the failed check. In this case, you can click `Details` for more information about how to get that check passing.
<img width="315" alt="Screenshot 2023-12-08 at 8 35 18 AM" src="https://github.com/cncf/tag-security/assets/21176439/501ae793-0173-4e38-8ea2-57dca65ab1ea">

2023-12-08 16:26 UTC, eddie-knight commented on assessments/projects/open-telemetry/self-assessment-template.md
> +# Self-assessment
```suggestion
# Open Telemetry Self-assessment
```

2023-12-10 08:02 UTC, ragashreeshekar requested changes
Thanks for the PR @PrathamGupta and team, appreciate the efforts.
I have completed first pass of review. Please feel free to reach out here or on slack for any questions and clarifications.

Along with addressing the comments, kindly update the PR branch with the latest content in the repo as this branch is out-of-date with the base branch.

2023-12-13 07:57 UTC, PrathamGupta commented on assessments/projects/open-telemetry/self-assessment-template.md
We have updated our PR with removing all the template content and tailored it for these needs. We have also corrected all the checks and will keep the PR updated for these checks in the future.

2023-12-13 08:00 UTC, PrathamGupta commented
> Thanks for the PR @PrathamGupta and team, appreciate the efforts. I have completed first pass of review. Please feel free to reach out here or on slack for any questions and clarifications.
> 
> Along with addressing the comments, kindly update the PR branch with the latest content in the repo as this branch is out-of-date with the base branch.

Thank you @ragashreeshekar for reviewing our work! We have updated the PR branch with the latest content in the repo and will be updated regularly till the PR has been reviewed completely.

2023-12-13 08:58 UTC, PrathamGupta commented on assessments/projects/open-telemetry/self-assessment.md
> +* The agents must authenticate themselves to the backend systems where the data is sent.
We have updated the same for Non Goals and we will also try to update the goals and add more details.

2023-12-13 20:41 UTC, PrathamGupta commented on assessments/projects/open-telemetry/self-assessment.md
> +**Security**
We have updated the goals of the document and increased the scope in this section.

Thanks for the feedback

2023-12-13 20:43 UTC, PrathamGupta commented on assessments/projects/open-telemetry/self-assessment.md
> +* **OpenTelemetry**: Same
Noted and changed.

Thanks for the feedback!

2023-12-13 20:45 UTC, PrathamGupta commented on assessments/projects/open-telemetry/self-assessment.md
> +* **Cilium**: Not applicable
The things which are not applicable are removed. 

Thanks for feedback!

2023-12-13 20:55 UTC, PrathamGupta commented on assessments/projects/open-telemetry/self-assessment.md
> +### CII Best Practices
We have added this as a recommendation for the project!

2023-12-13 20:57 UTC, PrathamGupta commented
@ragashreeshekar We have updated the PR with updates from your suggestions! Please let us know your thoughts about the assessment now! 

Thanks!

2023-12-13 20:57 UTC, PrathamGupta commented
@torinvdb We are currently in the process of making the changes you have suggested and going through your feedback

2023-12-13 21:04 UTC, PrathamGupta commented on assessments/projects/open-telemetry/self-assessment.md
> +
We have added this disclaimer again! We removed it on our assumption that this was not necessary, but we know understand the use of this disclaimer!

Thanks for the feedback

2023-12-14 17:42 UTC, PrathamGupta commented on assessments/projects/open-telemetry/self-assessment.md
> +### Ecosystem
We have added the reference to our assessment as well

2023-12-14 17:43 UTC, PrathamGupta commented on assessments/projects/open-telemetry/self-assessment.md
> +OpenTelemetry is an Observability framework and toolkit designed to create and manage telemetry data such as traces, metrics, and logs. Opentelemetry provides a standard protocol for dealing with tel
We have changed this in our assessment

2023-12-14 17:49 UTC, PrathamGupta commented on assessments/projects/open-telemetry/self-assessment.md
> +As these components are the primary source of incoming data, they also serve as the primary attack surface. A hypothetical attacker may be able to deliver a malicious payload by simply performing an
We have reviewed and changed this as well.

2023-12-14 18:13 UTC, PrathamGupta commented on assessments/projects/open-telemetry/self-assessment.md
> +The OpenTelemetry Collector is a vendor-agnostic implementation of how to receive, process and export telemetry data. It consists of multiple components: Receivers, Processors, Exporters, and Extensi
We shall change this in other sections as well

2023-12-14 18:32 UTC, PrathamGupta commented on assessments/projects/open-telemetry/self-assessment.md
> +All in all, this document helps explain this CNCF open source project, pave the way for the project to seek graduation, provide clear guidance during the incubation process, and bring a more transpar
Thank you for the insights regarding this and we have changed this in our assessment as well

2023-12-14 18:49 UTC, PrathamGupta commented on assessments/projects/open-telemetry/self-assessment.md
> +* OpenTelemetry makes generating, collecting, and exporting data from applications easy. We can use OpenTelemetry for system monitoring and then use a visual monitoring system to integrate the data s
We have added one example of use case in Kubernetes from the specifications mentioned on the websites. Let us know if we should add for more of the integrations

2023-12-14 20:38 UTC, PrathamGupta commented on assessments/projects/open-telemetry/self-assessment.md
> +In case of anomalies or incidents detected through telemetry data, alerts are generated. The alerting mechanism is secured to prevent false alerts and ensure that alerts reach the correct recipients.
We have ammended the same and answered some of the questions to our best ability.

2024-01-16 18:27 UTC, torinvdb commented on assessments/projects/open-telemetry/self-assessment.md
> +The Self-assessment is the initial document for projects to begin thinking about the security of the project, determining gaps in their security, and preparing any security documentation for their us
```suggestion
# OpenTelemetry Security Self Assessment

This assessment was created by community members as part of the [Security Pals](https://github.com/cncf/tag-security/issues/1102) process and is currently pending changes from the maintainer team.

The Self-assessment is the initial document for projects to begin thinking about the security of the project, determining gaps in their security, and preparing any security documentation for their users. This document is ideal for projects currently in the CNCF sandbox as well as projects that are looking to receive a joint assessment and currently in CNCF **Incubation**.
```
@ragashreeshekar

2024-01-16 20:07 UTC, ragashreeshekar approved these changes

2024-01-17 16:05 UTC, JustinCappos commented on assessments/projects/open-telemetry/self-assessment.md
> +[comment]: # (The Final Draft of Self Assessment has been completed on Dec 14, 2023: 5:40 EST)
```suggestion
```

2024-01-17 16:06 UTC, JustinCappos approved these changes
LGTM.  Ready to merge!

2024-01-17 16:07 UTC, merged