Antrea Project Security Self-Assessment - Security Pals
cncf/tag-security pull request #1190
Opened 2023-12-07 02:11 UTC by molofgarb

Created and added first draft for Antrea Project Security Self-Assessment.

We are still finalizing the implementation of feedback from the Antrea maintainers for a couple of sub-sections. The PR will be updated by force-pushes as we finish our revisions.

Please feel free to share your feedback on the security self-assessment!

2023-12-08 15:57 UTC, eddie-knight commented
Hi there, and thanks for your work on this self assessment!

I noticed that you included an SBOM along with the self assessment. There are two reasons that jump to the front of my mind for why this isn't needed...

1. SBOMs should be associated with releases, as the bill of materials is only accurate and useful if it is created at build time and associated to a particular point in the code history.
1. If you need to link to an SBOM for some reason in the self-assessment, you can just provide a link out to the latest build artifacts that contain an SBOM.

We still have plenty more to review, but as a starter— could you please remove the SBOM from this PR?

2023-12-08 21:41 UTC, molofgarb commented
> Hi there, and thanks for your work on this self assessment!
> 
> I noticed that you included an SBOM along with the self assessment. There are two reasons that jump to the front of my mind for why this isn't needed...
> 
>     1. SBOMs should be associated with releases, as the bill of materials is only accurate and useful if it is created at build time and associated to a particular point in the code history.
> 
>     2. If you need to link to an SBOM for some reason in the self-assessment, you can just provide a link out to the latest build artifacts that contain an SBOM.
> 
> 
> We still have plenty more to review, but as a starter— could you please remove the SBOM from this PR?

Hi Eddie, thank you for your feedback! We initially included the SBOM because a section for the SBOM is present in the [self-assessment template](https://github.com/cncf/tag-security/blob/main/assessments/guide/self-assessment.md). Your points are right though and we have removed the SBOM and its section in the self-assessment from our latest force push.

2023-12-11 09:00 UTC, ragashreeshekar requested changes
Thanks for the PR @molofgarb and team, appreciate the efforts.
I have completed first pass of review. Please feel free to reach out here or on slack for any questions and clarifications.

Along with addressing the comments, kindly update the PR branch with the latest content in the repo as this branch is out-of-date with the base branch.

2023-12-11 19:25 UTC, molofgarb commented
In our previous push, we have added a table to the "Related Projects and Vendors" section to briefly compare CNI projects.

2023-12-11 19:27 UTC, molofgarb commented
Thank you for your feedback @ragashreeshekar! We will work on adding your suggested changes and let you know once we have resolved them.

2023-12-12 03:34 UTC, molofgarb commented on assessments/projects/antrea/self-assessment.md
> +| Languages | Go, Shell, PowerShell, Makefile, Dockerfile, Jinja |
We have provided a link to a website where an SBOM for the current version of Antrea can be downloaded

2023-12-12 03:35 UTC, molofgarb commented on assessments/projects/antrea/self-assessment.md
> +### Threat Model
The threat model has been moved to the appendix

2023-12-12 03:40 UTC, molofgarb commented on assessments/projects/antrea/self-assessment.md
> +* Running a GitHub Action to
In that section, we mentioned that Antrea uses CodeQL, a SAST tool, and go-licenses, a SCA tool. We modified the section to explicitly mention those tools as SAST/SCA tools and organize it in a more readable manner. We also made an addition that states that Antrea does not have a secrets scanning service.

Please let us know if we have sufficient detail on the SAST/SCA/secrets scanning tools and if you think that it has been presented clearly.

2023-12-12 21:49 UTC, skyekim commented on assessments/projects/antrea/self-assessment.md
> +In a Kubernetes cluster, Antrea initializes the Antrea Agent and the Antrea Controller. The Antrea Agent sets up Open vSwitch (OVS) bridges on each Kubernetes Node to create connections between Pods
Thank you for the feedback. I have added more details to the Action section.

2023-12-13 03:25 UTC, molofgarb commented on assessments/projects/antrea/self-assessment.md
> +The primary goal of Antrea is to enhance network connectivity and security within Kubernetes clusters. Antrea is designed to ensure efficient and secure communication between containers, utilizing st
We have revised this section to focus on the goals of Antrea.

2024-01-16 19:04 UTC, molofgarb commented
Hi @torinvdb, thank you for your suggestions! We have added your changes to our most recent push.

2024-01-16 20:44 UTC, ragashreeshekar approved these changes

2024-01-17 16:20 UTC, JustinCappos approved these changes
Looks ready to merge!

2024-01-17 16:21 UTC, merged