OpenMetrics Project Security Self-Assessment - Security Pals
cncf/tag-security pull request #1199
Opened 2023-12-07 04:52 UTC by kc34251

OpenMetrics Project Self-Assessment

Kevin Chen
Tejushu Mutte
Justin Li
Kaartikeya Panjwani

Created and added first draft for OpenMetrics Project Security Self-Assessment.
Please feel free to share your feedback on the security self-assessment.

2023-12-08 16:34 UTC, eddie-knight commented on assessments/README.md
> +### 1) Reduce risk across the ecosystem
Please revert this change, as it doesn't contribute to this PR

2023-12-08 16:34 UTC, eddie-knight commented on assessments/projects/OpenMetrics/self-assessment.md
> +# Self-assessment outline
```suggestion
```

2023-12-08 16:36 UTC, eddie-knight commented
To match the naming convention of this repository, please rename your project directory to use all lowercase

2023-12-10 05:46 UTC, MutteTejeshu commented
Hi @eddie-knight ,

Thank you for your initial comments. I have made the suggested changes as required.

2023-12-11 16:49 UTC, JustinCappos commented on assessments/projects/openmetrics/self-assessment.md
> +* Proceed with archiving OpenMetrics if project maintaners decide that there is not enough support and possibly fold the project into Prometheus.
Understood.  We'll judge the assessment on its merit but with the understanding that it may not make sense to merge it.

2024-01-17 19:07 UTC, ragashreeshekar commented on assessments/projects/openmetrics/self-assessment.md
> +[Security Assessments for Open Source Projects](https://training.linuxfoundation.org/express-learning/security-self-assessments-for-open-source-projects-lfel1005/).
```suggestion
```

2024-01-17 19:07 UTC, ragashreeshekar commented on assessments/projects/openmetrics/self-assessment.md
> +This self-assessment is created by the OpenMetrics team to perform an internal analysis of the project's security. It is not intended to provide a security audit of OpenMetrics, or function as an ind
```suggestion
This self-assessment is not intended to provide a security audit of OpenMetrics, or function as an independent assessment or attestation of OpenMetrics's security health.
```

2024-01-17 19:11 UTC, ragashreeshekar requested changes

2024-01-17 19:11 UTC, ragashreeshekar commented on assessments/projects/openmetrics/self-assessment.md
> +
```suggestion
```

2024-01-17 19:11 UTC, ragashreeshekar approved these changes

2024-01-18 03:37 UTC, merged