etcd Project Security Self-Assessment - Security Pals
cncf/tag-security pull request #1201
Opened 2023-12-07 08:02 UTC by qianxichen233

added etcd Project Security Self-Assessment Draft

Contributors:
Qianxi Chen
Hari Kishan Reddy Abbasani
Aryan Rai
Ashish Tiwari

2023-12-08 14:47 UTC, eddie-knight commented
Hi there! I'm just getting started looking at your pull request, and I noticed the DCO check is failing.

You can look at the checks section of the PR (I believe it should always be below the last comment) and look for a red X highlighting the failed check. In this case, you can click `Details` for more information about how to get that check passing.
<img width="315" alt="Screenshot 2023-12-08 at 8 35 18 AM" src="https://github.com/cncf/tag-security/assets/21176439/501ae793-0173-4e38-8ea2-57dca65ab1ea">

2023-12-13 07:31 UTC, ragashreeshekar requested changes
Thanks for the PR @qianxichen233 and team, appreciate the efforts.
I have completed first pass of review and left a few comments on section that needs your attention. Please feel free to reach out here or on slack for any questions and clarifications.

Along with addressing the comments, kindly update the PR branch with the latest content in the repo as this branch is out-of-date with the base branch.

2023-12-13 07:31 UTC, ragashreeshekar commented on assessments/projects/etcd/self-assessment.md
> +## Table of contents
Please provide a heading to this document in the format of "<project name> Security Self Assessment"

2023-12-13 07:31 UTC, ragashreeshekar commented on assessments/projects/etcd/self-assessment.md
> +This self-assessment is created by the etcd team to perform an internal analysis of the
Can you please specify at the top which member of the maintainer team acted as an author on this? (Or otherwise rephrase)

2023-12-13 07:31 UTC, ragashreeshekar commented on assessments/projects/etcd/self-assessment.md
> +**Communication Channels**
Please add references to these channels.

2023-12-13 07:31 UTC, ragashreeshekar commented on assessments/projects/etcd/self-assessment.md
> +## Threat Modeling with STRIDE
Please include this in another file within the same folder, and link it in the appendix.

2023-12-14 05:53 UTC, qianxichen233 commented
Thanks a lot @ragashreeshekar , our team has updated our assessment

2023-12-28 15:19 UTC, jmhbnz commented on assessments/projects/etcd/Threat Modeling.md
> +**Threat:** An attacker could impersonate a legitimate Etcd member to gain unauthorized access to the cluster or disrupt its operation.
Nit: etcd should be lowercase throughout this document. 

```suggestion
**Threat:** An attacker could impersonate a legitimate etcd member to gain unauthorized access to the cluster or disrupt its operation.
```

2023-12-29 07:13 UTC, qianxichen233 commented
Thanks a lot, we just fixed it

2024-01-17 03:08 UTC, ragashreeshekar approved these changes

2024-01-17 16:58 UTC, JustinCappos approved these changes
This is solid.  It is ready to merge.

2024-01-17 16:59 UTC, JustinCappos commented
Waiting to merge until clarity about whether this belongs under the K8S SIG or not...

2024-01-24 22:26 UTC, eddie-knight commented
@aladewberry has let us know that the etcd assessment tracking should be taken over by K8s SIG Security. We can close this PR in the meantime.

@qianxichen233— If you're interested in continuing your contribution, I recommend you connect with Ala to make sure this work is properly migrated to the correct repo and aligned with the SIG Security efforts

ref: https://cloud-native.slack.com/archives/CDJ7MLT8S/p1705437592831179

2024-01-24 23:53 UTC, closed without merging