Group 27 Self Assessment
cncf/tag-security pull request #1202
Opened 2023-12-08 03:39 UTC by SassyQuatch47

Self Assessment for CNCF Project containerd

2023-12-08 14:30 UTC, eddie-knight commented
Hi there! I'm just starting to take a look at this, and I noticed that your pull request name isn't very descriptive. 

If you take a look at the [Pull Requests](https://github.com/cncf/tag-security/pulls) page, you'll see that the pile can be a lot easier to navigate if we all use descriptive titles. That'll help reviewers move more quickly, and also it's a great practice to follow when you're doing future work on platforms like GitHub/GitLab/Bitbucket/etc.

Instead of `Group 27 self assessment` a better alternative might be `containerd self-assessment`

2023-12-08 16:42 UTC, eddie-knight commented
I also noticed the DCO check is failing.

You can look at the checks section of the PR (I believe it should always be below the last comment) and look for a red X highlighting the failed check. In this case, you can click `Details` for more information about how to get that check passing.
<img width="315" alt="Screenshot 2023-12-08 at 8 35 18 AM" src="https://github.com/cncf/tag-security/assets/21176439/501ae793-0173-4e38-8ea2-57dca65ab1ea">

2023-12-08 16:43 UTC, eddie-knight commented on Containerd/self-assessment.md
Please go back to ensure that no template text like this is included here or in the rest of the document

2023-12-08 16:44 UTC, eddie-knight commented on Containerd/self-assessment.md
> +# Self-assessment outline
Please go back to ensure that no template text like this is included here or in the rest of the document

2023-12-12 02:24 UTC, eddie-knight commented on assessments/Open_and_Secure_Early_Access.pdf
It appears that something got wonky with the commit history here. Same with the `_index.md` file linked below. Please check your history and clean it up accordingly.

2023-12-12 02:57 UTC, SassyQuatch47 commented on website/content/_index.md
> +- [Andrés Vega](https://github.com/anvega) (Technical Leader)
Corrected _index.md

2023-12-13 08:07 UTC, ragashreeshekar requested changes
Thanks for the PR @SassyQuatch47 and team, appreciate the efforts.
I have completed first pass of review and left a few comments on section that needs your attention. Please feel free to reach out here or on slack for any questions and clarifications.

2023-12-13 08:07 UTC, ragashreeshekar commented on Containerd/self-assessment.md
> +### Actions
This section talks about the various functions/benefits of this project however it is meant to showcase the individual parts of your system that interact to provide the desired functionality.  
Ref: https://github.com/cncf/tag-security/blob/main/assessments/guide/self-assessment.md#actors

Please update this section to include the right actors.

2023-12-13 08:07 UTC, ragashreeshekar commented on Containerd/self-assessment.md
> +This self-assessment is created by the Containerd team to perform an internal analysis of the project's security.  It is not intended to provide a security audit of Containerd, or function as an inde
Can you please specify at the top which member of the maintainer team acted as an author on this? (Or otherwise rephrase)

2023-12-13 08:07 UTC, ragashreeshekar commented on Containerd/self-assessment.md
> +* Related Projects / Vendors:
Please elaborate how these project/vendors relate to this project, and what the key differences between them are.

2023-12-14 22:08 UTC, Nate-Smithline approved these changes

2023-12-14 22:09 UTC, Nate-Smithline approved these changes

2023-12-15 05:43 UTC, sublimino commented on Containerd/self-assessment.md
> +# Self-assessment outline
This is superflous, see [this example](https://github.com/cncf/tag-security/pull/1181/files) for what to remove

```suggestion
```

2023-12-15 05:43 UTC, sublimino commented on Containerd/self-assessment.md
> +A table at the top for quick reference information, later used for indexing.
```suggestion
```

2023-12-15 05:43 UTC, sublimino commented on Containerd/self-assessment.md
> +use the table below as an example:
```suggestion
```

2023-12-15 05:45 UTC, sublimino commented on Containerd/self-assessment.md
> +Containerd is a Cloud Native Computing Foundation (CNCF) Project focused on providing the core functionalities for container orchestration. Specifically architected to focus on modularity and compati
```suggestion
Containerd is a container runtime focused on providing the core functionalities for managing container lifecycles. Specifically architected to focus on modularity and compatibility, it provides a secure and minimal approach making it a great option for integrating into different container orchestrators. 
```

2023-12-15 05:47 UTC, sublimino commented on Containerd/self-assessment.md
> +Originally developed by Docker, Inc. as an integral part of the Docker project, Containerd has evolved with the dynamic container ecosystem. Docker's decision to separate container runtime functional
```suggestion
Originally developed by Docker, Inc. as an integral part of the Docker project, containerd has evolved with the dynamic container ecosystem. Docker's decision to separate container runtime functionality from the runc project led to containerd, an independent project dedicated to container management.
```

2023-12-15 05:48 UTC, sublimino commented on Containerd/self-assessment.md
> +Aligned with the Open Container Initiative (OCI) specifications, Containerd ensures compatibility with other runtimes and tools adhering to the OCI standard. This compatibility facilitates easy trans
```suggestion
Aligned with the Open Container Initiative (OCI) specifications, containerd ensures compatibility with other runtimes and tools adhering to the OCI standard. This compatibility facilitates easy transitions between container runtimes supporting OCI.
```

Ensure the correct name `containerd` is used everywhere that it's not starting a sentence. See https://www.docker.com/blog/what-is-containerd-runtime/ for an example

2023-12-15 05:49 UTC, sublimino commented on Containerd/self-assessment.md
> +Role: Serves as the core orchestration engine, managing the complete lifecycle of containers.
```suggestion
Role: the core orchestration engine, managing the complete lifecycle of containers.
```

2023-12-15 05:51 UTC, sublimino commented on Containerd/self-assessment.md
> +Role: Acts as repositories for container images, collaborating with containerd in tasks such as image pulling, pushing, and managing metadata.
```suggestion
Role: Repositories for container images, providing storage and retrieval for containerd in tasks such as image pulling, pushing, and metadata management.
```

2023-12-15 05:52 UTC, sublimino commented on Containerd/self-assessment.md
> +This self-assessment was authored by Swati Baleri, Vivek Radhakrishnan, Swati Baleri, Sunny Li, and Nathan Smith with a format established by the Containerd maintainers. The purpose of this document
```suggestion
This self-assessment was authored by Swati Baleri, Vivek Radhakrishnan, Sunny Li, and Nathan Smith with a format established by the Containerd maintainers. The purpose of this document is to perform an internal analysis of the project's security.  It is not intended to provide a security audit of Containerd, or function as an independent assessment or attestation of Containerd's security health.
```

2024-01-30 17:28 UTC, ragashreeshekar commented
@SassyQuatch47 Kindly address the pending suggestions. We (maintainers) do not have the permissions to update the PR hence we look forward to your updates. In the event it is not feasible, feel free to extend the permissions to us and we are happy to make the updates on your behalf. Thanks!

2024-01-31 20:54 UTC, SassyQuatch47 commented
> @SassyQuatch47 Kindly address the pending suggestions. We (maintainers) do not have the permissions to update the PR hence we look forward to your updates. In the event it is not feasible, feel free to extend the permissions to us and we are happy to make the updates on your behalf. Thanks!

Hi @ragashreeshekar , I apologize for the delay. We have given you permissions to update this PR. If any further issues come up, do let us know and we'd be happy to help!

2024-06-12 13:35 UTC, eddie-knight approved these changes
@ragashreeshekar It looks like all of your changes were applied— can you please confirm and resolve the requested change?

2024-06-24 21:49 UTC, ragashreeshekar approved these changes

2024-10-23 17:12 UTC, merged