docs: Compliance Working Group details addition to security tag landing page
cncf/tag-security pull request #1238
Opened 2024-04-09 14:02 UTC by AleJo2995

2024-04-09 19:44 UTC, PushkarJ commented
Please hold as a few discussions are ongoing in preparation for merging this

2024-04-20 01:28 UTC, PushkarJ requested changes
Just added some minor language changes that make the charter clearer to understand :) happy to chat more if there is anything that needs discussion.

2024-04-20 01:28 UTC, PushkarJ commented on compliance/README.md
> +- Generating specific examples of compliance as code, normalized templates, and tools for automating these both technical and non-technical requirements, control assessment, data analyses, audit and
```suggestion
- Generating specific examples of compliance as code, normalized templates, and tools for automating these both technical and non-technical requirements, control assessment, data analysis, audit and 
```

2024-04-20 01:28 UTC, PushkarJ commented on compliance/README.md
> +- Identifications of areas of focus eg human workflows, automated workflows, analytical tools, audit and assessment tools, technical security controls that cut across components and systems and cloud
```suggestion
- Identifications of areas of focus e.g. human workflows, automated workflows, analytical tools, audit and assessment tools, technical security controls that cut across components and systems and clouds, etc
```

2024-04-20 01:28 UTC, PushkarJ commented on compliance/README.md
> +- Cross project focus on the projects and efforts the CNCF is funding, helping projects identify needs and providing subject matters to assist
```suggestion
- Cross project focus on the projects and efforts the CNCF is funding, helping projects identify needs and providing subject matter expertise to assist
```

2024-04-20 01:28 UTC, PushkarJ commented on compliance/README.md
> +- Growing CNCF external relationships with interested parties, eg NIST and other compliance standards bodies such as FINOS, OSCAL, OpenSSF
```suggestion
- Growing CNCF external relationships with interested parties, e.g. NIST and other compliance standards bodies such as FINOS, OSCAL, OpenSSF
```

2024-04-20 01:28 UTC, PushkarJ commented on compliance/README.md
> +Takumi Yanagawa
Can we add everyone's GitHub handles in front of the names?

2024-04-22 15:31 UTC, AleJo2995 commented on README.md
> +Weekly meetings at 10:00 AM ET (60 min)
How cool 👍

2024-04-23 00:07 UTC, PushkarJ commented
Thanks @AleJo2995 can you please fix the linting errors?

2024-04-23 00:10 UTC, PushkarJ commented
I committed a couple of residual suggestions too.

2024-04-24 19:50 UTC, AleJo2995 commented
Also, if you see Spelling check is complaining about names and last names? How should I fix this?

<img width="1136" alt="image" src="https://github.com/cncf/tag-security/assets/8278478/3c74be0a-b91e-47c1-9844-ce4883698e84">

2024-04-25 01:45 UTC, PushkarJ commented
I ran the checks for you now. 

Try cspell enable and disable for ignoring names https://cspell.org/configuration/document-settings/

2024-04-25 17:56 UTC, AleJo2995 commented
@PushkarJ I have made the changes for the first to checks to pass, but for the one with the links I am not being able to solve it. What I am curious about is why it is failing if I haven't changed anything there 😅

2024-04-25 21:48 UTC, PushkarJ commented
You can ignore the links errors. Only three linting errors remaining :) after that we are good to go

2024-05-02 15:07 UTC, AleJo2995 commented
@PushkarJ I have done the changes for the trailing spaces that were problematic. I think this is now good to go. Thanks 👍

2024-05-02 16:42 UTC, PushkarJ approved these changes

2024-05-02 21:58 UTC, mnm678 approved these changes

2024-05-03 00:53 UTC, merged