Add John Kjell to TLs
cncf/tag-security pull request #1267
Opened 2024-06-06 17:37 UTC by anvega

adds @jkjell  
adds three tables to the README to better organize the list of Security TAG members

2024-06-06 17:54 UTC, JustinCappos requested changes
typo

2024-06-06 17:54 UTC, JustinCappos commented on README.md
> +| John Jkell    | TestifySec                 | @jkjell       |
typo
```suggestion
| John Kjell    | TestifySec                 | @jkjell       |
```

2024-06-06 17:59 UTC, anvega commented on README.md
> +| John Jkell    | TestifySec                 | @jkjell       |
Good catch!

2024-06-06 18:56 UTC, mnm678 reviewed
Other than the linting error, lgtm

2024-06-06 18:56 UTC, mnm678 commented on README.md
> +| Marina Moore          | NYU                    | October, 2023 - October, 2025 | @mnm678   |
```suggestion
| Marina Moore          | Independent                  | October, 2023 - October, 2025 | @mnm678   |
```

2024-06-07 16:40 UTC, PushkarJ approved these changes
Preview looks good on website from mobile too

2024-06-07 19:33 UTC, JustinCappos approved these changes

2024-06-07 22:33 UTC, merged