Dragonfly Project Security Self-Assessment
cncf/tag-security pull request #1326
Opened 2024-07-18 10:07 UTC by gaius-qi

Dragonfly Project Self-Assessment

Authors: Wenbo Qi(@gaius-qi)

Security reviewers: Tao Peng(@bergwolf), Wenbo Qi(@gaius-qi), Song Yan(@imeoer), Akash HR(akashhr), Xiongxiong Yuan(@yxxhero), Yiyang Huang(@hyy0322)

Created and added first draft for Dragonfly Project Security Self-Assessment.
Please feel free to share your feedback on the security self-assessment.

2024-07-18 19:24 UTC, JustinCappos commented
Okay, are you interested in a TAG Security Joint assessment?  If so, can you open an issue and request one?  (Prior issue #302 was closed due to inactivity)

2024-07-19 02:48 UTC, gaius-qi commented
> Okay, are you interested in a TAG Security Joint assessment? If so, can you open an issue and request one? (Prior issue #302 was closed due to inactivity)

Thanks @JustinCappos. I think it's good! Dragonfly needs a TAG Security Joint assessment. 😊

Issue: https://github.com/cncf/tag-security/issues/1327

2024-07-19 12:09 UTC, eddie-knight requested changes
The format and high-level content follow the template as expected. I made one suggestion to improve the SBOM link, but after that this looks ready to merge.

2024-07-23 03:59 UTC, gaius-qi commented on community/assessments/projects/dragonfly/self-assessment.md
> +| SBOM              | [FOSSA Scan](https://app.fossa.com/projects/git%2Bgithub.com%2Fdragonflyoss%2FDragonfly2/refs/branch/main/1f1b9886ab07742745250233bb3acd7790ecfaaa/preview) |
Thanks!

2024-07-31 12:17 UTC, merged