Create folder for WG content
cncf/tag-security pull request #1377
Opened 2024-09-30 04:55 UTC by vikas-agarwal76

2024-09-30 04:56 UTC, vikas-agarwal76 commented
Creating a content folder to store content (documents, compliance artifacts JSONs, etc.) created by Compliance WG.

2024-10-01 13:52 UTC, mnm678 approved these changes

2024-10-01 16:59 UTC, brandtkeller requested changes

2024-10-01 16:59 UTC, brandtkeller commented on community/working-groups/compliance/content/readme.md
> +This folder contains content created by Compliance WG
I'll take a look at the current warnings we are seeing the linting process. Nonetheless the linting action is failing as this file needs a top level H1.

2024-10-08 14:49 UTC, brandtkeller commented on community/working-groups/compliance/content/readme.md
> +This folder contains content created by Compliance WG
Appreciated

2024-10-08 14:52 UTC, brandtkeller reviewed
Branch just needs to be rebased to bring it up-to-date.

2024-10-09 05:12 UTC, vikas-agarwal76 commented
> Branch just needs to be rebased to bring it up-to-date.

done

2024-10-21 05:14 UTC, vikas-agarwal76 commented
@brandtkeller I rebased the branch as suggested by you. Kindly merge.

2024-10-21 17:09 UTC, brandtkeller approved these changes

2024-10-21 17:13 UTC, brandtkeller commented
No issues with the current state. 

Provided this is a placeholder for others to contribute and iterate in a central location - than looks good to me. 

I would recommend adding context in your PR descriptions towards why the change should be made. This placeholder will be published to the website and I would usually recommend adding this directory when you have changes to be proposed that include substance.

2024-10-21 17:14 UTC, merged