Add Software Supply Chain Best Practices v2 markdown
cncf/tag-security pull request #1396
Opened 2024-10-29 20:48 UTC by mnm678

The Software Supply Chain working group has been working on an update to the Software Supply Chain Best Practices Paper. This is the markdown version of the document we have been working on.

2024-10-29 22:55 UTC, brandtkeller commented
@mnm678 To what extent do you want to resolve the linter findings before merging this? No hard opinions here - might be a few spelling items worth review.

2024-10-31 14:54 UTC, jkjell commented on community/working-groups/supply-chain-security/suply-chain-security-paper-v2/SSCBPv2.md
> +# Scope: {#scope:}
It looks like GitHub auto-generates this heading ids: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#section-links.

2024-10-31 19:27 UTC, jkjell commented
I made this PR for the linter config which should resolve those. I agree that this should be allowed. https://github.com/cncf/tag-security/pull/1397

2024-11-06 00:16 UTC, brandtkeller reviewed
Minor callouts - feel free to consider these against the source-of-truth and otherwise resolve. 

I will follow-up with resolving these comments to approve if helpful.

2024-11-06 14:53 UTC, mnm678 commented
Thanks @brandtkeller! Feedback applied

2024-11-06 15:57 UTC, brandtkeller requested changes

2024-11-06 15:57 UTC, brandtkeller commented on community/working-groups/supply-chain-security/suply-chain-security-paper-v2/SSCBPv2.md
> +You may thing that it’s the problem of those providing the software.
```suggestion
You may think that it’s the problem of those providing the software.
```

2024-11-06 20:09 UTC, brandtkeller commented on community/working-groups/supply-chain-security/suply-chain-security-paper-v2/SSCBPv2.md
> +**Storage:** Attestations should be stored after verification for future use.
@mnm678 If I am looking at this change correctly - this can be consumed by the **Verification** bullet point item - is that intended?

2024-11-06 20:57 UTC, mnm678 commented on community/working-groups/supply-chain-security/suply-chain-security-paper-v2/SSCBPv2.md
> +**Storage:** Attestations should be stored after verification for future use.
Oh, it looks like the * was removed somehow, fixing now

2024-11-08 17:11 UTC, brandtkeller commented on community/working-groups/supply-chain-security/suply-chain-security-paper-v2/SSCBPv2.md
> +**Storage:** Attestations should be stored after verification for future use.
This is the only remaining conversation I have open to resolve before approval.

2024-11-08 17:57 UTC, mnm678 commented on community/working-groups/supply-chain-security/suply-chain-security-paper-v2/SSCBPv2.md
> +**Storage:** Attestations should be stored after verification for future use.
I missed that my push failed. Should be fixed now

2024-11-08 18:15 UTC, brandtkeller approved these changes
Content looks great - all of my concerns were resolved.

2024-11-08 19:08 UTC, merged