Updating the Makefile script on the website to work natively with MacOS.
cncf/tag-security pull request #1417
Opened 2024-12-04 02:01 UTC by pedroignacio13

After having some issues setting up the environment locally on MacOS, we figured it out what the problem was.
This PR adapts the Makefile script to work correctly when setting up the environment for local development.

Thanks Brandt and Eddie for the help on this issue!

2024-12-04 16:03 UTC, mrcdb commented
I am not sure if this is run in CI as well, wouldn't it have an impact as the "new" sed instruction would always run? I am wondering if there would be a better way of running the script for MacOS vs Linux (e.g. with a flag or something like that)

2024-12-05 01:31 UTC, pedroignacio13 commented
I'll let this PR open and try to find alternatives to this.
Let me know if you have something on your mind.

2024-12-13 22:51 UTC, brandtkeller requested changes
I agree with @mrcdb - this doesn't work with linux (and the expected CI) processes natively. 

Until such a time where this workflow is refactored - we may want to consider a conditional for macos/linux OR requiring gnu-sed on macos development environments.

2024-12-14 14:49 UTC, eddie-knight reviewed
Suggested changes will modify this to just being a comment so that it has the necessary info, but still defaults to working for CI builds

@pedroignacio13

2024-12-14 14:49 UTC, eddie-knight commented on website/Makefile
> +		sed -i "" "1s/^/$$text_to_prepend/" "$$file"; \
```suggestion
		sed -i "1s/^/$$text_to_prepend/" "$$file"; \
```

2025-03-27 22:53 UTC, eddie-knight approved these changes

2025-03-27 22:53 UTC, eddie-knight commented
@brandtkeller I've modified this to only contain the instructional comment for developer instruction, which is definitely needed.

2025-03-27 23:05 UTC, brandtkeller approved these changes

2025-03-27 23:06 UTC, merged