Add whitepaper directory structure and assessment
cncf/tag-security pull request #611
Opened 2021-05-05 02:34 UTC by rjulian

Additionally added relevant README to whitepaper directory, update top level README to reflect existence of whitepaper.

Will add whitepaper markdown once out of draft status.

2021-05-07 19:36 UTC, TheFoxAtWork commented on supply-chain-security/README.md
> +SIG-Security has put work into a comprehensive software supply chain whitepaper
STAG (Security Technical Advisory Group)

2021-05-07 19:37 UTC, TheFoxAtWork commented on supply-chain-security/README.md
> +# Supply Chain Security Whitepaper
```suggestion
# Supply Chain Security Paper
```

2021-05-07 19:37 UTC, TheFoxAtWork commented on supply-chain-security/README.md
> +out [the whitepaper](./supply-chain-security-whitepaper/software-supply-chain-security-whitepaper.md) and corollary [secure supply chain assessment document](./supply-chain-security-whitepaper/secure
```suggestion
out [the paper](./supply-chain-security-whitepaper/software-supply-chain-security-whitepaper.md) and corollary [secure supply chain assessment document](./supply-chain-security-whitepaper/secure-supply-chain-assessment.md) to learn more. 
```

2021-05-07 19:38 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/README.md
> +The Software Supply Chain Security Whitepaper is a SIG-Security effort
```suggestion
The Software Supply Chain Security Paper is a STAG effort 
```

2021-05-07 19:38 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/README.md
> +The Software Supply Chain Security Whitepaper (SSCSWP) is intended to be a living
```suggestion
The Software Supply Chain Security Paper (SSCSWP) is intended to be a living 
```

2021-05-07 19:39 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/README.md
> +Updates to the whitepaper, suggestions for updates, or discussion for updates
```suggestion
Updates to the paper, suggestions for updates, or discussion for updates
```

2021-05-07 19:39 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/README.md
> +The living SSCSWP is maintained in [markdown](https://github.com/cncf/sig-security/blob/master/supply-chain-security/software-supply-chain-security-whitepaper.md) and all updates will be made in
```suggestion
The living SSCSP is maintained in [markdown](https://github.com/cncf/sig-security/blob/master/supply-chain-security/software-supply-chain-security-whitepaper.md) and all updates will be made in
```

2021-05-07 19:39 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/README.md
> +All members of the community are welcome to contribute updates to the SSCSWP.
```suggestion
All members of the community are welcome to contribute updates to the SSCSP.
```

2021-05-07 19:40 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/README.md
> +of the Technical Leads and Co-Chairs of the SIG.
```suggestion
of the Technical Leads and Co-Chairs of the STAG.
```

2021-05-07 19:40 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/README.md
> +for the SSCSWP: [#sig-security-supply-chain-wg](https://cloud-native.slack.com/archives/C01KL0B4LKC) to request a review.
```suggestion
for the SSCSP: [#sig-security-supply-chain-wg](https://cloud-native.slack.com/archives/C01KL0B4LKC) to request a review.
```

2021-05-07 19:40 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/README.md
> +occur, the SSCSWP working group will assess and determine if a new major version
```suggestion
occur, the SSCSP working group will assess and determine if a new major version
```

2021-05-07 19:41 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/README.md
> +solicited to the CNCF SIG-Security and TOC mailing list for review, at a minimum.
```suggestion
solicited to the CNCF STAG and TOC mailing list for review, at a minimum.
```

2021-05-07 19:41 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/README.md
> +Upon completion of review, the SIG-Security TOC Liaison shall provide final
```suggestion
Upon completion of review, the STAG TOC Liaison shall provide final
```

2021-05-07 19:42 UTC, TheFoxAtWork requested changes
Need to change some acronyms to be more inclusive as well as support the SIG > STAG rename.  I think we are ready for the full conversion to MD once @lizrice finalizes her comments and we adjudicate.

2021-05-13 00:05 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/README.md
> +"suggestion" and "whitepaper".
Agreed.  Call it "supply chain" @lumjjb

2021-05-13 00:07 UTC, TheFoxAtWork commented on supply-chain-security/README.md
> +# Supply Chain Security Paper
```suggestion
# Supply chain security paper
```

2021-05-13 00:07 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/README.md
> +Software Supply Chain Security Whitepaper
```suggestion
Software Supply Chain Security Paper
```

2021-05-13 00:08 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/README.md
> +"suggestion" and "whitepaper".
```suggestion
"suggestion" and "supplychain".
```

2021-05-13 00:11 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/README.md
> +occur, the SSCSP working group will assess and determine if a new major version
I think governance docs are a larger discussion for papers going forward and should definitely be added.  #621

2021-05-13 00:11 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/secure-supply-chain-assessment.md
> +# Evaluating your Supply Chain Security
```suggestion
# Evaluating your supply chain security
```

2021-05-13 00:12 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/secure-supply-chain-assessment.md
> +# Evaluating your Supply Chain Security
```suggestion
# Evaluating your supply chain security
```

2021-05-13 00:12 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/secure-supply-chain-assessment.md
> +## A Framework for Supply Chain Evaluation
```suggestion
## A framework for supply chain evaluation
```

2021-05-13 00:13 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/secure-supply-chain-assessment.md
> +### Verify Source Code
```suggestion
### Verify source code
```

2021-05-13 00:13 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/secure-supply-chain-assessment.md
> +### Verify Materials
```suggestion
### Verify materials
```

2021-05-13 00:13 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/secure-supply-chain-assessment.md
> +### Protecting Build Pipelines
```suggestion
### Protecting build pipelines
```

2021-05-13 00:13 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-whitepaper/secure-supply-chain-assessment.md
> +### Protecting Artefacts and Deployments
```suggestion
### Protecting artefacts and deployments
```

2021-05-13 00:15 UTC, TheFoxAtWork approved these changes
LGTM @lumjjb please double check and if nothing found in err please merge in so we can get the paper added to the repo in the correct location.

2021-05-13 01:36 UTC, lumjjb commented
Sorry, but teeny tiny minor nit, could we rename the directory from `whitepaper` to `paper`.

2021-05-13 01:44 UTC, merged