docs: add php supply chain security incident
cncf/tag-security pull request #618
Opened 2021-05-12 08:50 UTC by lirantal

Adding the PHP supply chain security incident to the list of 2021 

Fixes #601

2021-05-12 10:45 UTC, joshuagl commented on supply-chain-security/compromises/2021/php.md
> +* Write access to the repository's source migrated out of a self-built karma system and now restricted only to members of the PHP organization.
Can we expand on organisation? Is that the GitHub Organisation? Or some other mechanism for identifying developers? If it is GitHub, we should probably move the switch to using GitHub to be the first item in the list.

2021-05-12 17:25 UTC, lirantal commented on supply-chain-security/compromises/2021/php.md
> +* Write access to the repository's source migrated out of a self-built karma system and now restricted only to members of the PHP organization.
Indeed, will update.

2021-05-12 17:25 UTC, lirantal commented on supply-chain-security/compromises/2021/php.md
> +* Write access to the repository's source migrated out of a self-built karma system and now restricted only to members of the PHP organization.
Resolved.

2021-05-13 17:59 UTC, TheFoxAtWork requested changes
@lirantal please update the `compromises/README.md` with this incident so that its on the main page THANK YOU FOR DOING THIS!

2021-06-25 15:26 UTC, lirantal commented
@TheFoxAtWork apologies on the delay, only seeing your reply now :-)
Will accommodate the updates.

2021-06-25 15:36 UTC, lirantal commented
@TheFoxAtWork up to date now with the README change as well

2021-06-25 18:17 UTC, TheFoxAtWork approved these changes
LGTM thank you for tackling this!!

2021-06-25 18:17 UTC, merged

2021-06-25 18:40 UTC, lirantal commented
Thanks Emily!