Converted to Markdown
cncf/tag-security pull request #622
Opened 2021-05-13 14:22 UTC by jonmuk

* Converted google doc to markdown

* Included images in markdown

2021-05-13 14:28 UTC, TheFoxAtWork commented
Could you copy the paper content to a new file 'sscsp.md' under /supply-chain-security-paper/ and revert the README.md which has the governance info for how the paper gets updated?  

The main supply chain folder's readme will need updated with the deep link to the sscsp.md as will the paper's readme

this will keep a similar structure to the cnswp

2021-05-13 17:23 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-paper/sscsp.md.md
> +# **<span style="text-decoration:underline;">Draft</span>**: Software Supply Chain Best Practices
```suggestion
Shared with the CNCF community

# Software Supply Chain Best Practices
```

2021-05-13 17:26 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-paper/sscsp.md.md
> +  <tr>
```suggestion

## Metadata

| **Markdown** | | | |
| -- | -- | -- | -- |
| **Version** | **1.0** | 13 MAY 2021 | [Original working doc](https://docs.google.com/document/d/1VURD9rdEhiuqPdixhEozkHw01Tk6e2AaJVjBK3pK6Zc) |
| **Status** | WIP | In Review | **Approved** |

| **PDF** | |
| -- | -- |
| **Created** | TBD |
| **Last Reviewed** | TBD |
| **PDF Published** | TBD |
| **Release Version** | 1.0 | 
| **Final PDF Approvers** | [ ] @lizrice [ ] @justincormack  |

```

2021-05-13 17:28 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-paper/sscsp.md.md
> +
```suggestion

| **Originating Content and Review** | |
| -- | --|
| **Contributors** | Andres Vega @anvega, Emily Fox @TheFoxAtWork, Faisal Razzak @faisalrazzak, @apmarshall, Cole Kennedy @colek42,Mikhail Swift @mikhailswift, Jon Meadows @jonmuk, Aditya Sirish A Yelgundhalli @adityasaky, Nisha Kumar @nishakm, Joshua Lock @joshuagl, Andrew Martin @sublimino, @mnm678 , Vinod Anandan @VinodAnandan, Magno Logan @magnologan, @rjulian @lumjjb @mlieberman85 @garrying |
| **Reviewers** | @aspanner @mike-ensor @timfong888 @alexbarbato @voor, Alok Raj @ak-secops | 

## Index

```

2021-05-13 17:47 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-paper/sscsp.md.md
> +**Reviewing**:  If reviewing, be sure to highlight the particular section or line of text with a question, comment, etc. in the google doc via the comment feature.  If the question is more thematic s
```suggestion
-  [Executive Summary](#executive-summary)
-  [Introduction](#introduction)
  -  [Audience](#audience)
  -  [Scope](#scope)
    -  [Non-Goals](#non-goals)
  -  [Assumptions](#assumptions)
    -  [Shared Responsibility](#shared-responsibility)
    -  [Projects and Products](#projects-and-products)
  -  [Assurance Personas and Risk Appetite](#assurance-personas-and-risk-appetite)
    -  [Assurance Requirements](#assurance-requirements)
    -  [Risk Environments](#risk-environments)
  -  [Securing the Software Supply Chain](#securing-the-software-supply-chain)
  -  [General Guidance](#general-guidance)
-  [Securing the Source Code](#securing-the-source-code)
  - [Secure Authentication](#secure-authentication)
-  [Securing Materials](#securing-materials)
  -  [Second and Third-Party Risk Management](#second-and-third-party-risk-management)
-  [Securing Build Pipelines](#securing-build-pipelines)
  -  [Build Infrastructure](#build-infrastructure)
    -  [Build Step and Worker](#build-step-and-worker)
    -  [Build Pipeline to Create Build Stage Images](#build-pipeline-to-create-build-images)
    -  [Pipeline Orchestrator](#pipeline-orchestrator)
    -  [A Sample Build Pipeline](#a-sample-build-pipeline)
    -  [Recommendations for Reproducible Builds](#recommendations-for-reproducible-builds)
-  [Securing Artifacts](#securing-artifacts)
  -  [Encryption](#encryption)
-  [Securing Deployments](#securing-deployments)
-  [Prior Art and References](#prior-art-and-references)
-  [Appendix I](#appendix-i-containers)
-  [Footnotes](#notes)
```

2021-05-13 17:47 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-paper/sscsp.md.md
> +# Prior Art / References:
```suggestion
# Prior Art and References:
```

2021-05-13 17:49 UTC, TheFoxAtWork requested changes
Several suggestions have been added and the file name is incorrect and will need changed from `sscsp.md.md` to `sscsp.md`

2021-05-13 22:02 UTC, jonmuk commented
updated as requested

2021-05-13 22:22 UTC, TheFoxAtWork approved these changes
lgtm!!!!

2021-05-13 22:40 UTC, lumjjb reviewed
The index is messed up but other than that i suggested a couple minor formatting changes, if not LGTM

2021-05-13 22:40 UTC, lumjjb commented on supply-chain-security/supply-chain-security-paper/sscsp.md
> +-  [Executive Summary](#executive-summary)
The index is flat, this is because of the multiple spaces between the bullet and the start of text i believe.

2021-05-13 22:40 UTC, lumjjb commented on supply-chain-security/supply-chain-security-paper/sscsp.md
> +#
```suggestion
```

2021-05-13 22:40 UTC, lumjjb commented on supply-chain-security/supply-chain-security-paper/sscsp.md
> +##
```suggestion
```

2021-05-13 22:40 UTC, lumjjb commented on supply-chain-security/supply-chain-security-paper/sscsp.md
> +#
```suggestion
```

2021-05-13 22:40 UTC, lumjjb commented on supply-chain-security/supply-chain-security-paper/sscsp.md
> +Clients receiving software artefacts from the distribution mechanism must be able to verify the integrity of the downloaded files. It’s also vital that the view a client has of the repository is cons
```suggestion
Clients receiving software artefacts from the distribution mechanism must be able to verify the integrity of the downloaded files. It’s also vital that the view a client has of the repository is consistent and up to date so the client sees the latest version of all the files it has access to. This is especially necessary for highly volatile repositories.
```

2021-05-13 22:40 UTC, lumjjb commented on supply-chain-security/supply-chain-security-paper/sscsp.md
> + \
```suggestion
 
```

2021-05-13 22:40 UTC, lumjjb commented on supply-chain-security/supply-chain-security-paper/sscsp.md
> +#
```suggestion
```

2021-05-13 22:40 UTC, lumjjb commented on supply-chain-security/supply-chain-security-paper/sscsp.md
> +
```suggestion
```

2021-05-13 22:40 UTC, lumjjb commented on supply-chain-security/supply-chain-security-paper/sscsp.md
> +
```suggestion
```

2021-05-13 22:40 UTC, lumjjb commented on supply-chain-security/supply-chain-security-paper/sscsp.md
> +
```suggestion
```

2021-05-14 04:42 UTC, anvega requested changes
One nit: Please create a directory to group all image files.

2021-05-14 12:56 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-paper/sscsp.md
> +-  [Executive Summary](#executive-summary)
```suggestion
- [Executive Summary](#executive-summary)
```

2021-05-14 12:57 UTC, TheFoxAtWork commented on supply-chain-security/supply-chain-security-paper/sscsp.md
> +-  [Footnotes](#notes)
```suggestion
- [Introduction](#introduction)
  - [Audience](#audience)
  - [Scope](#scope)
    - [Non-Goals](#non-goals)
  - [Assumptions](#assumptions)
    - [Shared Responsibility](#shared-responsibility)
    - [Projects and Products](#projects-and-products)
  - [Assurance Personas and Risk Appetite](#assurance-personas-and-risk-appetite)
    - [Assurance Requirements](#assurance-requirements)
    - [Risk Environments](#risk-environments)
  - [Securing the Software Supply Chain](#securing-the-software-supply-chain)
  - [General Guidance](#general-guidance)
- [Securing the Source Code](#securing-the-source-code)
  - [Secure Authentication](#secure-authentication)
- [Securing Materials](#securing-materials)
  - [Second and Third-Party Risk Management](#second-and-third-party-risk-management)
- [Securing Build Pipelines](#securing-build-pipelines)
  - [Build Infrastructure](#build-infrastructure)
    - [Build Step and Worker](#build-step-and-worker)
    - [Build Pipeline to Create Build Stage Images](#build-pipeline-to-create-build-images)
    - [Pipeline Orchestrator](#pipeline-orchestrator)
    - [A Sample Build Pipeline](#a-sample-build-pipeline)
    - [Recommendations for Reproducible Builds](#recommendations-for-reproducible-builds)
- [Securing Artifacts](#securing-artifacts)
  - [Encryption](#encryption)
- [Securing Deployments](#securing-deployments)
- [Prior Art and References](#prior-art-and-references)
- [Appendix I](#appendix-i-containers)
- [Footnotes](#notes)
```

2021-05-14 13:07 UTC, lumjjb commented on supply-chain-security/supply-chain-security-paper/sscsp.md
> +- [Footnotes](#notes)
```suggestion
- [Executive Summary](#executive-summary)
- [Introduction](#introduction)
- [Securing the Source Code](#securing-the-source-code)
- [Securing Materials](#securing-materials)
- [Securing Build Pipelines](#securing-build-pipelines)
- [Securing Artifacts](#securing-artifacts)
- [Securing Deployments](#securing-deployments)
- [Prior Art and References](#prior-art-and-references)
- [Appendix I](#appendix-i-containers)
- [Appendix II)(#appendix-ii-software-groups)
```
make consistent with PDF

2021-05-14 13:08 UTC, lumjjb approved these changes
LGTM!

2021-05-14 13:26 UTC, merged