What: Uploaded more logos, corrected table, etc.
cncf/tag-security pull request #717
Opened 2021-06-25 21:05 UTC by TheFoxAtWork

Why:

* We were missing logos in the design readme
* the logo for the main readme was not darkmode friendly #687

This change addresses the need by:

* Created new logos
* Updated the table
* added the new dark mode safe logo to the main readme.

2021-07-01 02:00 UTC, ultrasaurus commented
fyi -- to disable the spell-check (where appropriate) you can add a comment above wherever the unique words are (if you don't want to add to the repo-wide config, which would likely be the case here):
```
<!-- cSpell:disable -->
```

2021-07-01 17:47 UTC, ultrasaurus commented
also, prolly even better, would be to ignore specific words

<!-- cSpell:ignore darkmodesafe explainability -->

though common acronyms like "APAC" should prolly go in the repo-wide config `ci/spelling-config.json`

2021-07-01 17:51 UTC, ultrasaurus commented
oh, I just realized ALL of the errors are in the main README -- will try to work on separate PR to fix that!

2021-07-03 23:25 UTC, ultrasaurus commented
updated branch, spell check passes -- yay!

2021-07-03 23:29 UTC, ultrasaurus commented
dark mode fixed, here's what the logo in the README looks like this PR:
![image](https://user-images.githubusercontent.com/41906/124368983-ca3aa200-dc1b-11eb-8d84-9aeb2d0af5b8.png)

2021-07-03 23:40 UTC, ultrasaurus commented
White logos should be displayed on grey background.  This is what it looks like for me:
![image](https://user-images.githubusercontent.com/41906/124369130-6d3feb80-dc1d-11eb-82cf-33558eb4d1c7.png)

2021-07-03 23:42 UTC, ultrasaurus requested changes
This is a great step forward, just a few small fixes and it'll be ready to merge.  See prior comments.

2021-07-03 23:42 UTC, ultrasaurus commented on design/README.md
> +        <td><img src="logo/Cloud-Native-Security-Horizontal-White.png" width="200"></td>
Please leave filenames consistent where possible.  Also, our style guide preferences all lower case filenames.

2021-07-03 23:47 UTC, ultrasaurus commented
on spellcheck, I didn't wait long enough, I guess... weird that it showed passing for a minute.  

I would suggest adding darkmodesafe to `/ci/spelling-config.json` since it shows up in a couple of files, but also ok IMHO if you want to use cspell:ignore locally in both files.

2021-07-08 14:29 UTC, TheFoxAtWork commented on design/README.md
> +        <td><img src="logo/Cloud-Native-Security-Horizontal-White.png" width="200"></td>
fixing.

2021-07-08 14:37 UTC, TheFoxAtWork commented
<img width="598" alt="pretty-logos" src="https://user-images.githubusercontent.com/33327273/124941075-84455b80-dfd8-11eb-91e9-932884e68f79.png">

2021-07-08 14:39 UTC, TheFoxAtWork commented
@ultrasaurus every change you requested should be resolved.  even added a preview of the new change!

2021-07-09 14:48 UTC, lumjjb reviewed
Looks good, trying another cspell fix

2021-07-09 14:48 UTC, lumjjb commented on ci/spelling-config.json
> +        "darkmodesafe"
i think the better fix for this is for cpell to ignore that line instead.

```suggestion
        "APAC",
```

2021-07-09 14:48 UTC, lumjjb commented on README.md
> +<img src="design/logo/cloud-native-security-horizontal-darkmodesafe.svg" alt="Cloud Native Security logo" width="400"/>
```suggestion
<!-- cspell:disable-next-line -->
<img src="design/logo/cloud-native-security-horizontal-darkmodesafe.svg" alt="Cloud Native Security logo" width="400"/>
```

2021-07-09 14:52 UTC, lumjjb commented
@ultrasaurus `<!-- cspell:disable-next-line -->` seems to work

2021-07-14 14:30 UTC, TheFoxAtWork commented
@ultrasaurus can you verify the changes were applied so this can be merged?

2021-07-14 18:13 UTC, lumjjb commented
Linked this PR to cspell issue https://github.com/cncf/tag-security/issues/724 to address, if not should be good to merge... @ultrasaurus if you can take a quick look and we can merge this PR

2021-08-04 20:25 UTC, ultrasaurus commented
filenames should be all lower case:
![image](https://user-images.githubusercontent.com/41906/128249669-80275b72-8670-4dad-b237-e9e798fe4ef8.png)

not sure if that's the reason or if there are additional issues that cause broken images links: 
![image](https://user-images.githubusercontent.com/41906/128249750-41c6159b-c8f2-4f86-b311-a779711ae516.png)

2021-08-04 21:17 UTC, TheFoxAtWork commented
@ultrasaurus looks like i've finally fixed it, it wasn't accepting the file rename which was why the images were broken.

2021-08-05 00:39 UTC, ultrasaurus reviewed
so close... not quite sure what the issue is, but dropping in a comment with what I'm seeing

2021-08-05 00:39 UTC, ultrasaurus commented on design/README.md
> +*Note: GitHub Flavored Markdown used in the Readme doesn't support background colors. The white logos below are displayed on the medium grey (#474756) in its row.*
Actually, it's not picking up that style.  It seems to be using a lighter grey
![image](https://user-images.githubusercontent.com/41906/128273200-80a052e7-a85e-4a49-877b-2b07d5e9a086.png)

when I look at using the browser inspector, I see...
![image](https://user-images.githubusercontent.com/41906/128273014-f7cac846-e84e-483f-a2b7-53b397024611.png)

It is using the value `#f6f8fa`
![image](https://user-images.githubusercontent.com/41906/128273056-f5222067-bfae-42dd-b3b2-973d4849e46d.png)

2021-08-05 00:56 UTC, ultrasaurus commented
@TheFoxAtWork looks like css is not supported by github, removed as part of the sanitization process: https://stackoverflow.com/questions/51956361/custom-css-file-for-readme-md-in-a-github-repo

I wonder if we could use the grey color swatch image as a background?  if github supports markup to overlay images or have background image or something

2021-08-05 00:58 UTC, ultrasaurus commented
.... OR was the note at the top of the file supposed to indicate that it looks incorrect in github, but would look correct rendered as HTML in a normal browser... if so, maybe it would be easier to just include explicit HTML, I dunno.  Confusing.

2021-08-05 13:38 UTC, TheFoxAtWork commented
@ultrasaurus i think i'll just render separate images just for the readme display with links to the source file without a background.

2021-08-05 14:13 UTC, TheFoxAtWork commented
<img width="1113" alt="Screen Shot 2021-08-05 at 10 05 36 AM" src="https://user-images.githubusercontent.com/33327273/128363812-e421cad4-fbbf-49d3-961a-ad3716cdba07.png">
okay - i've modified the table for the white logos so that they 'appear' to be displayed in the readme on the correct background with a link to take the user to the correct file with a transparent background.

2021-08-14 14:59 UTC, ultrasaurus approved these changes
Sorry for the delay.  Looks fine.  I don't love that it'll be harder to maintain, but reasonable trade-off.  In retrospect, the initial version against light gray wasn't so bad, and I think that would be ok too.

One note -- didn't check dark-mode, where black prolly has same problem, but I don't think that needs to block this merging in.

2021-08-17 13:43 UTC, merged