Add Contributors process for papers
cncf/tag-security pull request #820
Opened 2021-11-22 21:56 UTC by lumjjb

During initial Cloud Native Security Whitepaper, it was discussed how the attribution and authorship should be carried out for papers produced by the STAG.

2021-11-22 22:57 UTC, PushkarJ reviewed
Few minor typos or newline edits - otherwise looks good!

2021-11-22 22:57 UTC, PushkarJ commented on governance/paper-process.md
> +'near-complete' and can review it as a wholistic section.  #### Opinions
```suggestion
'near-complete' and can review it as a holistic section.  
#### Opinions
```

2021-11-22 22:57 UTC, PushkarJ commented on governance/paper-process.md
> +provides source content and is a matter of good practice.  ### Collaborative
```suggestion
provides source content and is a matter of good practice.  

### Collaborative
```

2021-11-22 22:57 UTC, PushkarJ commented on governance/paper-process.md
> +"Acknowledgements" section where appropriate.  appropriate.
```suggestion
"Acknowledgements" section where appropriate. 
```

2021-11-22 22:57 UTC, PushkarJ commented on governance/paper-process.md
> +#### Authorship, attribution and acknowledgements
Thank you for addressing a topic that could get thorny in a succinct and fair way!

2021-11-22 23:01 UTC, lumjjb commented
Sad, the --fix flag failed me :(

On Mon, Nov 22, 2021, 5:57 PM Pushkar Joglekar ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Few minor typos or newline edits - otherwise looks good!
> ------------------------------
>
> In governance/paper-process.md
> <https://github.com/cncf/tag-security/pull/820#discussion_r754694500>:
>
> > @@ -72,18 +75,23 @@ Once task assignment is complete, contributors can begin content rough-in.
>
>  ### Content rough-in
>
>
>
>  Assignees can provide content rough-in in a variety of ways.  They may provide
>
> -raw content in the form of phrases, disjointed paragraphs, bullets on the
>
> -topic, or they draft content in the form of completed paragraphs.  If leveraging
>
> -draft content, placing this content in quotes helps other reviewers know it is
>
> -'near-complete' and can review it as a wholistic section.
>
> -#### Opinions
>
> +raw content in the form of phrases, disjointed paragraphs, bullets on the topic,
>
> +or they draft content in the form of completed paragraphs.  If leveraging draft
>
> +content, placing this content in quotes helps other reviewers know it is
>
> +'near-complete' and can review it as a wholistic section.  #### Opinions
>
>
> ⬇️ Suggested change
>
> -'near-complete' and can review it as a wholistic section.  #### Opinions
>
> +'near-complete' and can review it as a holistic section.
>
> +#### Opinions
>
>
> ------------------------------
>
> In governance/paper-process.md
> <https://github.com/cncf/tag-security/pull/820#discussion_r754694744>:
>
> >
>
>  #### References
>
>
>
> -It is important that any references used to generate paper content be cited appropriate through footnotes and a references section as appropriate.  This ensures the reader may not only dig deep into a specific reference area but also provides source content and is a matter of good practice.
>
> -### Collaborative review
>
> +It is important that any references used to generate paper content be cited
>
> +appropriate through footnotes and a references section as appropriate.  This
>
> +ensures the reader may not only dig deep into a specific reference area but also
>
> +provides source content and is a matter of good practice.  ### Collaborative
>
>
> ⬇️ Suggested change
>
> -provides source content and is a matter of good practice.  ### Collaborative
>
> +provides source content and is a matter of good practice.
>
> +
>
> +### Collaborative
>
>
> ------------------------------
>
> In governance/paper-process.md
> <https://github.com/cncf/tag-security/pull/820#discussion_r754695536>:
>
> > +#### Authorship, attribution and acknowledgements
>
> +
>
> +Papers and other resources created from TAG-Security efforts are under the
>
> +authorship of TAG-Security, and all members who have made contributions to the
>
> +document (through writing, editing, creating illustrations, etc.) are considered
>
> +"Contributors". Members of the public or TAG-Security who have commented and
>
> +given feedback during the Request for Comment (RFC) period of during the
>
> +creation of the document are considered "Reviewers" of the project.
>
> +
>
> +Individuals/groups who have made huge contributions/impact on the work can be
>
> +acknowledged in an "Acknowledgements" section. This is to highlight stellar
>
> +contributions and commitments to individuals that have went above and beyond to
>
> +contribute to the project.
>
> +
>
> +Each document should contain a "Contributors", "Reviewers" and
>
> +"Acknowledgements" section where appropriate.  appropriate.
>
>
> ⬇️ Suggested change
>
> -"Acknowledgements" section where appropriate.  appropriate.
>
> +"Acknowledgements" section where appropriate.
>
>
> ------------------------------
>
> In governance/paper-process.md
> <https://github.com/cncf/tag-security/pull/820#discussion_r754695741>:
>
> > @@ -173,3 +209,20 @@ strongly recommended the paper lead coordinate with TAG leadership to engage the
>
>  CNCF team for posting a blog to summarize and link to the paper.  As community
>
>  events occur, it is also recommended that the TAG coordinate a submission to
>
>  community events (presentation) on the paper.
>
> +
>
> +#### Authorship, attribution and acknowledgements
>
>
> Thank you for addressing a topic that could get thorny in a succinct and
> fair way!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cncf/tag-security/pull/820#pullrequestreview-813096428>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXLDBWG6VJLXORN3KAR2B3UNLDF7ANCNFSM5ISBTIVA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-01 15:27 UTC, lumjjb commented on governance/paper-process.md
> +review
```suggestion
```

2021-12-01 15:30 UTC, lumjjb commented on governance/paper-process.md
> +"Acknowledgements" section where appropriate.
```suggestion
"Acknowledgements" section where appropriate.
```

2021-12-01 15:45 UTC, TheFoxAtWork commented on governance/paper-process.md
> +  * Note - these are documented then in the "Introduction > Assumptions"
```suggestion
  * Note - these are documented in the "Introduction > Assumptions"
```

2021-12-01 15:45 UTC, TheFoxAtWork commented on governance/paper-process.md
> +  * Note - these are documented then in the "Introduction > Scope > Goals" and
```suggestion
  * Note - these are documented in the "Introduction > Scope > Goals" and
```

2021-12-01 15:46 UTC, TheFoxAtWork commented on governance/paper-process.md
> +or they draft content in the form of completed paragraphs.  If leveraging draft
```suggestion
or draft content in the form of completed paragraphs.  If leveraging draft
```

2021-12-01 15:46 UTC, TheFoxAtWork commented on governance/paper-process.md
> +'near-complete' and can review it as a holistic section.
```suggestion
'near-complete' and it should be reviewed it as a holistic section.  
```

2021-12-01 15:51 UTC, TheFoxAtWork commented on governance/paper-process.md
> +the decision up to the reader.
```suggestion
controls implementation are expressed.  Authors should make every effort to 
discover the industry standard or practice and document it. If none exists 
and the suggested content cannot be collaboratively resolved, it is the duty 
of the authors to capture the different views with references, benefits, and 
drawbacks or contingencies in order to provide the reader with enough 
information to leave the decision up to the reader.
```

2021-12-01 15:59 UTC, TheFoxAtWork commented on governance/paper-process.md
> +appropriate through footnotes and a references section as appropriate.  This
```suggestion
appropriately through footnotes and within the references section.  This
```

2021-12-01 15:59 UTC, lumjjb commented on governance/paper-process.md
> +information to leave the decision up to the reader.
```suggestion
information to reach their own conclusion.
```

2021-12-01 16:00 UTC, TheFoxAtWork commented on governance/paper-process.md
> +ensures the reader may not only dig deep into a specific reference area but also
```suggestion
permits the reader to not only dig deep into a specific reference area but also
```

2021-12-01 16:01 UTC, TheFoxAtWork commented on governance/paper-process.md
>  meeting and decisively resolved.
```suggestion
meeting and decisively resolved. These should be clearly documented with justification in the notes.
```

2021-12-01 16:04 UTC, TheFoxAtWork commented on governance/paper-process.md
> +contributions and commitments to individuals that have went above and beyond to
```suggestion
contributions and commitments by individuals that have went above and beyond to
```

2021-12-01 16:05 UTC, TheFoxAtWork requested changes
a few nits and 1 significant update that needs committed.

2021-12-01 16:34 UTC, lumjjb commented
Made the changes, will do a full lint fix once all changes are final

2021-12-01 16:36 UTC, TheFoxAtWork approved these changes
LGTM

2022-01-07 17:13 UTC, merged