github.md
cncf/tag-security pull request #861
Opened 2022-02-09 15:53 UTC by dutchshark

Addressing issue #860

2022-04-14 21:39 UTC, PushkarJ requested changes

2022-04-14 21:39 UTC, PushkarJ commented on governance/github.md
> +This highly limits the amount of branches and stops having branches around for longer then needed.
```suggestion
## Housekeeping
To maintain the main branch in a feasible way the Pull Requests shall come
from forked repositories from tag-security. After which an unique name
should be assigned to identify what will be changed in the forked repository
by utilizing branches. 

After being merged the branch will be deleted.
Next contributions shall be in another fresh branch. 
This way we keep the repository clean and allows a faster acceptance as it's
clear what exactly is addressed.

This highly limits the amount of branches and stops having branches around
for longer then needed.
```

2022-04-14 21:44 UTC, PushkarJ commented on governance/github.md
> +This highly limits the amount of branches and stops having branches around for longer then needed.
@dutchshark if you commit this suggestion, I believe it should allow us to pass the CI lint job

2022-07-01 23:22 UTC, ultrasaurus commented
From a process perspective this seems like a good change!

2022-07-29 23:00 UTC, PushkarJ commented on governance/github.md
> +This highly limits the amount of branches and stops having branches around for longer then needed.
Committed this suggestion as the original author has been unavailable

2022-07-29 23:01 UTC, PushkarJ approved these changes

2022-07-29 23:09 UTC, PushkarJ commented
Lint errors should be fixed once this is merged: https://github.com/cncf/tag-security/pull/964 

We should update the branch to let the CI run again

2022-08-01 17:35 UTC, PushkarJ commented on governance/github.md
> +repository by utilizing branches.
```suggestion
repository by utilizing branches.
```

2022-08-01 17:35 UTC, PushkarJ commented on governance/github.md
> +Next contributions shall be in another fresh branch.
```suggestion
Next contributions shall be in another fresh branch.
```

2022-08-01 17:35 UTC, PushkarJ commented on governance/github.md
> +## Housekeeping
```suggestion
## Housekeeping

```

2022-08-01 17:39 UTC, merged