Update tools.md
cncf/tag-security pull request #864
Opened 2022-02-17 15:02 UTC by lumjjb

2022-02-17 18:31 UTC, PushkarJ requested changes

2022-02-17 20:42 UTC, achetal01 approved these changes

2022-02-18 04:19 UTC, lumjjb commented on governance/tools.md
>  - [Pandoc](https://pandoc.org/)
what's example 35?

2022-02-18 04:19 UTC, lumjjb commented on governance/tools.md
>  - [Pandoc](https://pandoc.org/)
oh i think i see what you mean, we probably want to be more verbose about it

2022-02-18 22:45 UTC, PushkarJ commented on governance/tools.md
>  - [Pandoc](https://pandoc.org/)
Updated the suggested commit

2022-02-21 21:58 UTC, lumjjb commented on governance/tools.md
> +helpful suggestions to others in the group.
```suggestion
This document contains a set of tools that will be useful to security reviewers
and project leads. This is not an endorsement of any vendor or open source
project, rather a collection of what has been useful to individuals to share
helpful suggestions to others in the group.
```

2022-02-21 21:58 UTC, lumjjb commented on governance/tools.md
> +- [Pandoc](https://pandoc.org/demos.html): Check example in this link to convert `docx` to `markdown`
```suggestion

- [Pandoc](https://pandoc.org/demos.html): Check example in this link to convert
`docx` to `markdown` 
```

2022-02-21 22:33 UTC, lumjjb commented on governance/tools.md
> +`docx` to `markdown`
```suggestion
`docx` to `markdown`
```

2022-02-22 17:02 UTC, PushkarJ approved these changes

2022-02-22 17:03 UTC, merged