docs: update table of contents
cncf/tag-security pull request #917
Opened 2022-05-30 05:21 UTC by lirantal

Updating the table of contents to include the new `Malicious Maintainer` type of compromise.

2022-06-02 23:40 UTC, PushkarJ requested changes

2022-06-02 23:40 UTC, PushkarJ commented on supply-chain-security/compromises/compromise-definitions.md
> +Occurs when the development machine, SDK, toolchains, or build kit have
```suggestion
Occurs when the development machine, SDK, tool chains, or build kit have
```

2022-06-02 23:40 UTC, PushkarJ commented on supply-chain-security/compromises/compromise-definitions.md
> +Occurs when the development machine, SDK, toolchains, or build kit have
This is mostly for spellcheck

2022-06-02 23:40 UTC, PushkarJ commented on supply-chain-security/compromises/compromise-definitions.md
> +regarding code signing key protection.  A more indepth explanation
```suggestion
regarding code signing key protection.  A more in depth explanation
```

2022-06-02 23:40 UTC, PushkarJ commented on supply-chain-security/compromises/compromise-definitions.md
> +regarding code signing key protection.  A more indepth explanation
Only for spellcheck reasons

2022-06-03 13:30 UTC, lirantal commented
Thank you @PushkarJ for the spelling checks!

2022-06-06 22:06 UTC, PushkarJ commented
@lirantal only DCO remaining before we can merge :)

2022-06-07 20:26 UTC, lirantal commented
@PushkarJ all ready on my end

2022-06-07 21:29 UTC, merged