Fix or Disable lint wherever needed
cncf/tag-security pull request #923
Opened 2022-06-01 21:46 UTC by PushkarJ

2022-06-06 22:09 UTC, PushkarJ commented
> [✖] https://eba.europa.eu/documents/10180/2170121/Final+draft+Recommendations+on+Cloud+Outsourcing+%28EBA-
> Rec-2017-03%29.pdf → Status: 404

This is a false positive CI failure as the link opens if you click on it :)

2022-06-15 20:55 UTC, TheFoxAtWork requested changes
Looks like the space in the link brackets should have been before the bracket.

2022-06-15 20:55 UTC, TheFoxAtWork commented on security-whitepaper/v2/cloud-native-security-whitepaper.md
> +The[CNCF Storage Whitepaper](https://bit.ly/cncf-storage-whitepaperV2) provides additional background on the concepts,
```suggestion
The [CNCF Storage Whitepaper](https://bit.ly/cncf-storage-whitepaperV2) provides additional background on the concepts,
```

2022-06-15 20:55 UTC, TheFoxAtWork commented on security-whitepaper/v2/cloud-native-security-whitepaper.md
> +and[security boundaries](https://www.oreilly.com/library/view/cissp-certified-information/9780470276884/9780470276884_security_boundaries.html)
```suggestion
and [security boundaries](https://www.oreilly.com/library/view/cissp-certified-information/9780470276884/9780470276884_security_boundaries.html)
```

2022-06-15 20:55 UTC, TheFoxAtWork commented on security-whitepaper/v2/cloud-native-security-whitepaper.md
> +four-step[OWASP threat modeling](https://owasp.org/www-community/Threat_Modeling) recommended for cloud native
```suggestion
four-step [OWASP threat modeling](https://owasp.org/www-community/Threat_Modeling) recommended for cloud native
```

2022-06-15 23:31 UTC, TheFoxAtWork approved these changes
LGTM thanks @PushkarJ

2022-06-15 23:32 UTC, TheFoxAtWork commented
@PushkarJ seems like there is one broken link for EBA.  I leave it to you if you want to merge this in, otherwise it looks great to me.

2022-06-16 05:31 UTC, PushkarJ commented
@TheFoxAtWork thank you! I replaced with a link that loaded fast enough for link checker to turn green!

2022-06-16 05:32 UTC, merged