docs: add new rubygems supply chain security story
cncf/tag-security pull request #981
Opened 2022-09-26 16:05 UTC by lirantal

Signed-off-by: Liran Tal <liran.tal@gmail.com>

2022-09-27 16:21 UTC, mnm678 commented
Thanks for submitting this! Could you fix the typos tagged by the linter and add the compromise to the [index](https://github.com/cncf/tag-security/tree/main/supply-chain-security/compromises)?

2022-10-09 09:26 UTC, lirantal commented
@mnm678 fixed typos, rebased, and added DCO.

2022-10-28 18:13 UTC, szh requested changes
Some grammar nit picks :)

2022-10-28 18:13 UTC, szh commented on supply-chain-security/compromises/2022/rubygems-override.md
> +referring to the RubyGems.org website which is the home of
```suggestion
affects the RubyGems.org website which is the home of
```

2022-10-28 18:13 UTC, szh commented on supply-chain-security/compromises/2022/rubygems-override.md
> +the same packages as new ones, with modified code, and potentially
```suggestion
the same packages as new, with modified code and potentially
```

2022-10-28 18:13 UTC, szh commented on supply-chain-security/compromises/2022/rubygems-override.md
> +impact could still be devastating if went unnoticed.
```suggestion
impact could still be devastating if it were to go unnoticed.
```

2022-10-28 18:13 UTC, szh commented on supply-chain-security/compromises/2022/rubygems-override.md
> +known case of malicious exploitation they are aware of.
```suggestion
known cases of malicious exploitation they are aware of.
```

2022-11-06 06:58 UTC, lirantal commented
Ready to land ✅

2022-11-06 21:26 UTC, szh approved these changes
LGTM! Will need @lumjjb, @PushkarJ or someone else with write access to merge.

2023-02-14 21:29 UTC, szh commented
Any reason this hasn't been merged yet?

2023-05-21 17:13 UTC, lirantal commented
I'll update the index entry, missed that!

2023-05-21 20:42 UTC, lirantal commented
@szh @mnm678 ready now with the index up to date.

2023-05-21 21:05 UTC, closed without merging

2023-05-21 21:14 UTC, lirantal commented
Apologies on the pings. I had a mess with this branch and had to start over. PR changes moved to this new one: https://github.com/cncf/tag-security/pull/1078